name: "Emby Server+"
version: "1.0.0"
slug: "emby_custom"
description: "Сервер Emby на основе AlanZhai"
arch:
  - aarch64
  - amd64
init: false
startup: application
ports:
  8096/tcp: 8096
  8920/tcp: 8920
map:
  - media:rw
  - share:rw
options: {}
schema: {}
image: "alanzhai/embycrack"
